src/api/config/routes.rb
OBSApi::Application.routes.draw do
  draw :webui
  draw :api
end

src/api/app/models/user.rb
require 'kconv'
require 'api_error'

class User < ApplicationRecord
  include CanRenderModel
  include Flipper::Identifier

  # Keep in sync with states defined in db/schema.rb
  STATES = %w[unconfirmed confirmed locked deleted subaccount].freeze
  NOBODY_LOGIN = '_nobody_'.freeze
  MAX_BIOGRAPHY_LENGTH_ALLOWED = 250

  enum :color_theme, { 'system' => 0, 'light' => 1, 'dark' => 2 }

  # disable validations because there can be users which don't have a bcrypt
  # password yet. this is for backwards compatibility
  has_secure_password validations: false

  has_many :watched_items, dependent: :destroy
  has_many :groups_users, inverse_of: :user
  has_many :roles_users, inverse_of: :user
  has_many :relationships, inverse_of: :user, dependent: :destroy

  has_many :comments, dependent: :destroy, inverse_of: :user
  has_many :status_messages
  has_many :tokens, class_name: 'Token', dependent: :destroy, inverse_of: :executor, foreign_key: :executor_id

  has_and_belongs_to_many :shared_workflow_tokens,
                          class_name: 'Token::Workflow',
                          join_table: :workflow_token_users,
                          association_foreign_key: :token_id,
                          dependent: :destroy,
                          inverse_of: :token_workflow

  has_many :reviews, dependent: :nullify

  has_many :event_subscriptions, inverse_of: :user

  belongs_to :owner, class_name: 'User', optional: true
  has_many :subaccounts, class_name: 'User', foreign_key: 'owner_id'

  has_many :requests_created, foreign_key: 'creator', primary_key: :login, class_name: 'BsRequest'

  # users have a n:m relation to group
  has_and_belongs_to_many :groups, -> { distinct }
  # users have a n:m relation to roles
  has_and_belongs_to_many :roles, -> { distinct }

  has_many :bs_request_actions_seen_by_users, dependent: :nullify
  has_many :bs_request_actions_seen, through: :bs_request_actions_seen_by_users, source: :bs_request_action

  has_one :ec2_configuration, class_name: 'Cloud::Ec2::Configuration', dependent: :destroy
  has_one :azure_configuration, class_name: 'Cloud::Azure::Configuration', dependent: :destroy
  has_many :upload_jobs, class_name: 'Cloud::User::UploadJob', dependent: :destroy

  has_many :notifications, -> { order(created_at: :desc) }, as: :subscriber, dependent: :destroy

  has_many :commit_activities

  has_many :status_message_acknowledgements, dependent: :destroy
  has_many :acknowledged_status_messages, through: :status_message_acknowledgements, class_name: 'StatusMessage', source: 'status_message'

  has_many :disabled_beta_features, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :nullify
  has_many :submitted_reports, class_name: 'Report'

  has_many :moderated_comments, class_name: 'Comment', foreign_key: 'moderator_id'
  has_many :decisions, foreign_key: 'moderator_id'
  has_many :canned_responses, dependent: :destroy
  has_many :blocked_users, foreign_key: 'blocker_id', dependent: :destroy

  scope :confirmed, -> { where(state: 'confirmed') }
  scope :all_without_nobody, -> { where.not(login: NOBODY_LOGIN) }
  scope :not_deleted, -> { where.not(state: 'deleted') }
  scope :not_locked, -> { where.not(state: 'locked') }
  scope :active, -> { confirmed.or(User.unscoped.where(state: :subaccount, owner: User.unscoped.confirmed)) }
  scope :staff, -> { joins(:roles).where('roles.title' => 'Staff') }
  scope :admins, -> { joins(:roles).where('roles.title' => 'Admin') }
  scope :moderators, -> { joins(:roles).where('roles.title' => 'Moderator') }

  scope :in_beta, -> { where(in_beta: true) }
  scope :in_rollout, -> { where(in_rollout: true) }

  scope :list, lambda {
    all_without_nobody.includes(:owner).select(:id, :login, :email, :state, :realname, :owner_id, :updated_at, :ignore_auth_services)
  }

  scope :with_email, -> { where.not(email: [nil, '']) }

  scope :seen_since, ->(since) { where('last_logged_in_at > ?', since) }

  validates :login, :state, presence: { message: 'must be given' }

  validates :login,
            uniqueness: { case_sensitive: true, message: 'is the name of an already existing user' }

  validates :login,
            format: { with: /\A[\w $\^\-.#*+&'"]*\z/,
                      message: 'must not contain invalid characters' }
  validates :login,
            length: { in: 2..100, allow_nil: true,
                      too_long: 'must have less than 100 characters',
                      too_short: 'must have more than two characters' }

  validates :state, inclusion: { in: STATES }

  validate :validate_state

  # We want a valid email address. Note that the checking done here is very
  # rough. Email adresses are hard to validate now domain names may include
  # language specific characters and user names can be about anything anyway.
  # However, this is not *so* bad since users have to answer on their email
  # to confirm their registration.
  validates :email,
            format: { with: /\A([\w\-.\#$%&!?*'+=(){}|~]+)@([0-9a-zA-Z\-.\#$%&!?*'=(){}|~]+)+\z/,
                      message: 'must be a valid email address',
                      allow_blank: true }

  # we disabled has_secure_password's validations. therefore we need to do manual validations
  validate :password_validation
  validates :password, length: { minimum: 6, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED }, allow_nil: true
  validates :password, confirmation: true, allow_blank: true
  validates :biography, length: { maximum: MAX_BIOGRAPHY_LENGTH_ALLOWED }
  validates :rss_secret, uniqueness: true, length: { maximum: 200 }, allow_blank: true
  validates :color_theme, inclusion: { in: color_themes.keys }, if: -> { Flipper.enabled?('color_themes') }

  after_create :create_home_project, :measure_create
  after_update :measure_delete

  def create_home_project
    # avoid errors during seeding
    return if login.in?([NOBODY_LOGIN, 'Admin'])
    # may be disabled via Configuration setting
    return unless can_create_project?(home_project_name)

    # find or create the project
    project = Project.find_by(name: home_project_name)
    return if project

    project = Project.create!(name: home_project_name)
    project.commit_user = self
    # make the user maintainer
    project.relationships.create!(user: self, role: Role.find_by_title('maintainer'))
    project.store
    @home_project = project
  end

  # Inform ActiveModel::Dirty that changes are persistent now
  after_save :changes_applied

  # When a record object is initialized, we set the state and the login failure
  # count to unconfirmed/0 when it has not been set yet.
  before_validation(on: :create) do
    self.state ||= 'unconfirmed'

    # Set the last login time etc. when the record is created at first.
    self.last_logged_in_at = Time.zone.today

    self.login_failure_count = 0 if login_failure_count.nil?
  end

  def self.autocomplete_token(prefix = '')
    autocomplete_login(prefix).collect { |user| { name: user } }
  end

  def self.autocomplete_login(prefix = '')
    AutocompleteFinder::User.new(User.not_deleted.not_locked, prefix).call.pluck(:login)
  end

  # the default state of a user based on the api configuration
  def self.default_user_state
    ::Configuration.registration == 'confirmation' ? 'unconfirmed' : 'confirmed'
  end

  def self.create_user_with_fake_pw!(attributes = {})
    create!(attributes.merge(password: SecureRandom.base64(48)))
  end

  # This static method tries to find a user with the given login and password
  # in the database. Returns the user or nil if they could not be found
  def self.find_with_credentials(login, password)
    find_by(login: login)&.authenticate_via_password(password)
  end

  # Currently logged in user or nobody user if there is no user logged in.
  # Use this to check permissions, but don't treat it as logged in user. Check
  # nobody? on the returned object
  def self.possibly_nobody
    current || nobody
  end

  # Currently logged in user. Will throw an exception if no user is logged in.
  # So the controller needs to require login if using this (or models using it)
  def self.session!
    raise ArgumentError, 'Requiring user, but found nobody' unless session

    current
  end

  # Currently logged in user or nil
  def self.session
    current if current && !current.nobody?
  end

  def self.admin_session?
    current && current.admin?
  end

  # set the user as current session user (should be real user)
  def self.session=(user)
    Thread.current[:user] = user
  end

  def self.default_admin
    admin = CONFIG['default_admin'] || 'Admin'
    user = User.find_by!(login: admin)
    raise NotFoundError, "Admin not found, user #{admin} has not admin permissions" unless user.admin?

    user
  end

  def self.find_nobody!
    User.create_with(email: 'nobody@localhost',
                     realname: 'Anonymous User',
                     state: 'locked',
                     password: '123456').find_or_create_by(login: NOBODY_LOGIN)
  end

  def self.find_by_login!(login)
    user = not_deleted.find_by(login: login)
    return user if user

    raise NotFoundError, "Couldn't find User with login = #{login}"
  end

  # some users have last_logged_in_at empty
  def last_logged_in_at
    self[:last_logged_in_at] || created_at
  end

  def away?
    last_logged_in_at < 3.months.ago
  end

  def authenticate_via_password(password)
    if authenticate(password)
      mark_login!
      self
    else
      count_login_failure
      nil
    end
  end

  def validate_state
    # check that the state transition is valid
    errors.add(:state, 'must be a valid new state from the current state') unless state_transition_allowed?(state_was, state)
  end

  # This method checks whether the given value equals the password when
  # hashed with this user's password hash type. Returns a boolean.
  def deprecated_password_equals?(value)
    hash_string(value) == deprecated_password
  end

  def authenticate(unencrypted_password)

src/api/app/controllers/concerns/webui/manage_relationships.rb
module Webui::ManageRelationships
  extend ActiveSupport::Concern

  def save_person_or_group(what)
    authorize main_object, :update?
    begin
      Relationship::AddRole.new(main_object, Role.find_by_title!(params[:role]), check: true, user: params[:userid], group: params[:groupid]).add_role # report error on duplicate
      main_object.store
    rescue NotFoundError,
           Relationship::AddRole::SaveError => e
      flash[:error] = e.to_s
      return redirect_to(custom_users_path)
    end
    respond_to do |format|
      format.js { render json: {}, status: :ok }
      format.html do
        success_str = what == :person ? "user #{params[:userid]}" : "group #{params[:groupid]}"
        flash[:success] = "Added #{success_str} with role #{params[:role]}"
        redirect_to custom_users_path
      end
    end
  end

  def custom_users_path
    url_for(action: :users, project: @project, package: @package)
  end

  def save_person
    save_person_or_group(:person)
  end

  def save_group
    save_person_or_group(:group)
  end

  def load_user_or_group
    login = params[:userid]
    title = params[:groupid]
    raise MissingParameterError, 'Neither user nor group given' unless login.present? || title.present?

    return User.find_by_login!(login) if login

    ::Group.find_by_title!(title)
  end

  def remove_role
    authorize main_object, :update?
    begin
      main_object.remove_role(load_user_or_group, Role.find_by_title(params[:role]))
      main_object.store
    rescue NotFoundError => e
      flash[:error] = e.to_s
    end
    respond_to do |format|
      format.js { render json: {}, status: :ok }
      format.html do
        flash[:success] = if params[:userid]
                            "Removed user #{params[:userid]}"
                          else
                            "Removed group '#{params[:groupid]}'"
                          end
        redirect_to custom_users_path
      end
    end
  end
end

src/api/app/controllers/concerns/webui/notifications_filter.rb
module Webui::NotificationsFilter
  extend ActiveSupport::Concern

  # It's a sequence of multiple conditions combinations
  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/PerceivedComplexity
  def filter_notifications_by_kind(notifications, filter_kind)
    return notifications if filter_kind == ['all']

    relations_kind = []
    relations_kind << notifications.for_comments if filter_kind.include?('comments')
    relations_kind << notifications.for_requests if filter_kind.include?('requests')
    relations_kind << notifications.for_incoming_requests(User.session) if filter_kind.include?('incoming_requests')
    relations_kind << notifications.for_outgoing_requests(User.session) if filter_kind.include?('outgoing_requests')
    relations_kind << notifications.for_relationships_created if filter_kind.include?('relationships_created')
    relations_kind << notifications.for_relationships_deleted if filter_kind.include?('relationships_deleted')
    relations_kind << notifications.for_build_failures if filter_kind.include?('build_failures')
    relations_kind << notifications.for_reports if filter_kind.include?('reports')
    relations_kind << notifications.for_workflow_runs if filter_kind.include?('workflow_runs')
    relations_kind << notifications.for_appealed_decisions if filter_kind.include?('appealed_decisions')
    relations_kind << notifications.for_member_on_groups if filter_kind.include?('member_on_groups')

    notifications = notifications.merge(relations_kind.inject(:or)) unless relations_kind.empty?
    notifications
  end
  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/PerceivedComplexity

  def filter_notifications_by_state(notifications, filter_state)
    return notifications.merge(notifications.unread.or(notifications.read)) if filter_state == 'all'

    if filter_state == 'read'
      notifications.read
    elsif filter_state == 'unread'
      notifications.unread
    end
  end

  def filter_notifications_by_project(notifications, filter_project)
    relations_project = filter_project.map do |project_name|
      notifications.for_project_name(project_name)
    end

    notifications = notifications.merge(relations_project.inject(:or)) unless relations_project.empty?
    notifications
  end

  def filter_notifications_by_group(notifications, filter_group)
    relations_group = filter_group.map do |group_title|
      notifications.for_group_title(group_title)
    end

    notifications = notifications.merge(relations_group.inject(:or)) unless relations_group.empty?
    notifications
  end

  def filter_notifications_by_request_state(notifications, filter_request_state)
    relations_request_state = filter_request_state.map do |request_state|
      notifications.for_request_state(request_state)
    end

    return notifications if relations_request_state.empty?

    notifications.merge(relations_request_state.inject(:or))
  end

  def filter_notifications_by_report_decision(notifications, filter_report_decision)
    return notifications if filter_report_decision.empty?

    notifications = notifications.for_reports

    relations_report_decision = []
    if filter_report_decision.include?('with_decision')
      relations_report_decision << notifications.where.not(notifiable_id: Report.without_decision.select(:id))
    end
    if filter_report_decision.include?('without_decision')
      relations_report_decision << notifications.where(notifiable_id: Report.without_decision.select(:id))
    end

    notifications.merge(relations_report_decision.inject(:or))
  end

  def filter_notifications_by_reportable_type(notifications, filter_reportable_type)
    relations_reportable_type = filter_reportable_type.map do |reportable_type|
      notifications.where(notifiable_id: Report.where(reportable_type: reportable_type).select(:id))
    end

    return notifications if relations_reportable_type.empty?

    notifications = notifications.for_reports
    notifications.merge(relations_reportable_type.inject(:or))
  end
end

src/api/app/controllers/concerns/webui/notifications_handler.rb
module Webui::NotificationsHandler
  extend ActiveSupport::Concern

  def handle_notification
    return unless User.session && params[:notification_id]

    current_notification = Notification.find(params[:notification_id])

    return unless NotificationCommentPolicy.new(User.session, current_notification).update?

    current_notification
  end
end

src/api/app/controllers/webui/action_seen_by_users_controller.rb
class Webui::ActionSeenByUsersController < Webui::WebuiController
  before_action :require_login

  def toggle
    @action = BsRequestAction.find(params[:action_id])
    @user = User.session

    @action.toggle_seen_by(@user)

    respond_to do |format|
      format.js
    end
  end
end

src/api/app/controllers/webui/cloud/azure/upload_jobs_controller.rb
module Webui
  module Cloud
    module Azure
      class UploadJobsController < ::Webui::Cloud::UploadJobsController
        def new
          xml_object = OpenStruct.new(params.slice(:project, :package, :repository, :arch, :filename))
          @upload_job = ::Cloud::Backend::UploadJob.new(xml_object: xml_object)
        end

        private

        def validate_configuration_presence
          redirect_to cloud_azure_configuration_path if User.possibly_nobody.azure_configuration.blank?
        end

        def permitted_params
          params.require(:cloud_backend_upload_job).permit(
            :project, :package, :repository, :arch, :filename, :target,
            :image_name, :subscription, :container, :storage_account, :resource_group
          )
        end
      end
    end
  end
end

src/api/app/views/webui/users/_activity_date.html.haml
- max_count = 12

.h5
  Contributions on #{date}
- if activities_per_day[:commits].present?
  = activity_date_commits(activities_per_day[:commits])
- if activities_per_day[:requests_created].present?
  .h6.mt-3
    = pluralize(activities_per_day[:requests_created].size, 'request')
    created
  .m-2.ms-3
    - count = activities_per_day[:requests_created].size - max_count
    - activities_per_day[:requests_created][0..(max_count - 1)].each do |number|
      = link_to(number, request_show_path(number))
    = "and #{count} more" if count.positive?
- if activities_per_day[:requests_reviewed].present?
  .h6.mt-3
    = pluralize(activities_per_day[:requests_reviewed].values.sum, 'review')
    done
  .m-2.ms-3
    in requests:
    - count = activities_per_day[:requests_reviewed].size - max_count
    - activities_per_day[:requests_reviewed].keys[0..(max_count - 1)].each do |number|
      = link_to(number, request_show_path(number))
    = "and #{count} more" if count.positive?

- if activities_per_day[:comments].positive?
  .h6.mt-3
    = pluralize(activities_per_day[:comments], 'comment')
    written

src/api/app/views/webui/users/_breadcrumb_items.html.haml
- case action_name
  - when 'index'
    = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      Manage Users
  - when 'new'
    - if User.session
      = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      = @pagetitle.capitalize
  - when 'show'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      - if @is_displayed_user
        Your Profile
      - else
        Profile of #{@displayed_user}
  - when 'edit'
    = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item
      = link_to('Manage Users', users_path)
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      = @displayed_user

src/api/app/views/webui/users/_sign_up.html.haml
- submit_btn_text ||= 'Sign Up'

- if ::Configuration.proxy_auth_mode_enabled?
  - if CONFIG['proxy_auth_register_page'].blank?
    %p Sorry, signing up is currently disabled
  - else
    %p= link_to 'Use this link to Sign Up', proxy_auth_register_page
- else
  = form_tag(users_path, method: :post, class: 'sign-up', autocomplete: 'off') do
    .mb-3
      = label_tag 'login', 'Username:'
      = render partial: 'webui/shared/required_label_mark'
      = text_field_tag 'login', nil, placeholder: 'Username', autocomplete: 'off', class: 'form-control', required: true
    .mb-3
      = label_tag 'email', 'Email:'
      = render partial: 'webui/shared/required_label_mark'
      = text_field_tag 'email', nil, placeholder: 'Email address', autocomplete: 'off', class: 'form-control', type: 'email', required: true
    .mb-3
      = label_tag 'password', 'Password:'
      = render partial: 'webui/shared/required_label_mark'
      = password_field_tag :password, nil, id: 'pwd', placeholder: 'Enter a password', autocomplete: 'off', class: 'form-control', required: true
    .mb-3
      = label_tag 'password_confirmation', 'Password confirmation:'
      = render partial: 'webui/shared/required_label_mark'
      = password_field_tag(:password_confirmation, nil, id: 'pwd_confirmation', placeholder: 'Password confirmation', autocomplete: 'off',
        class: 'form-control', required: true)
    = hidden_field_tag 'register', 'true'
    = submit_tag submit_btn_text, class: 'btn btn-primary w-100'

    -# This should be refactored to avoid relying on global state
    - unless User.session # rubocop:disable ViewComponent/AvoidGlobalState
      .login-separator.text-center
        %hr.my-4
        %span.bg-card.px-3.text-muted or
      .text-center
        = link_to('Log In', new_session_path)

src/api/app/views/webui/users/edit.html.haml
- @pagetitle = "Edit User #{@displayed_user}"

.card.mb-3
  .card-body
    %h3= @pagetitle
    .col-md-6.ps-0
      = form_for(@displayed_user) do |form|
        = form.hidden_field(:login)
        .mb-3
          = form.label(:realname, 'Name:')
          = form.text_field(:realname, class: 'form-control')
        .mb-3
          = form.label(:email, 'Email:')
          = render partial: 'webui/shared/required_label_mark'
          = form.text_field(:email, required: true, email: true, class: 'form-control')
        .mb-3
          = form.collection_check_boxes(:role_ids, Role.global, :id, :title, {}) do |checkbox|
            .form-check
              = checkbox.check_box(class: 'form-check-input')
              = checkbox.label(class: 'form-check-label')
        .mb-3
          = form.collection_radio_buttons(:state, User::STATES - ['subaccount'], :to_s, :to_s, class: 'form-check-input') do |radio|
            .form-check.custom-control-inline
              = radio.radio_button(class: 'form-check-input')
              = radio.label(class: 'form-check-label')
        - if User.admin_session?
          .mb-3
            .form-check
              = form.check_box(:ignore_auth_services, { class: 'form-check-input' }, true)
              = form.label(:ignore_auth_services, 'Local user', class: 'form-check-label')
        = form.submit('Update', class: 'btn btn-primary', data: { disable_with: 'Updating...' })

src/api/app/views/webui/users/edit_account.js.erb
$('#flash').empty();
$('.in-place-editing').animate({
  opacity: 0.25
}, 400, function() {
  scrollToInPlace();
  $('.in-place-editing').html("<%= escape_javascript(render(partial: 'webui/user/edit_account_form', locals: { displayed_user: @displayed_user, role_titles: @role_titles, account_edit_link: @account_edit_link})) %>");
  $('.in-place-editing').animate({ opacity: 1 }, 400, function() {
    $("form *[autofocus='autofocus']").focus();
  });
});

src/api/app/views/webui/users/index.html.haml
- @pagetitle = 'Manage Users'

.card.mb-3
  = render partial: 'webui/configuration/tabs'
  .card-body
    %h3= @pagetitle
    %table.responsive.table.table-sm.table-bordered.table-hover#user-table{ data: { source: users_path } }
      %thead
        %tr
          %th.all
            User
          %th
            Real Name
          %th
            Local User
          %th.all
            State
          %th.all
            Actions
      %tbody

    .pt-4
      = link_to(new_user_path(pagetitle: 'create user', submit_btn_text: 'create', title: 'Create User')) do
        %i.fas.fa-plus-circle.text-primary
        Create User
    - confirmation_text = "Please confirm deletion of '#{content_tag(:span, '', class: 'user-login')}'"
    = render DeleteConfirmationDialogComponent.new(modal_id: 'delete-user-modal',
                                                   method: :delete,
                                                   options: { modal_title: 'Delete user?', remote: false,
                                                              confirmation_text: sanitize(confirmation_text, tags: ['span']) }) do |component|
      - component.with_text_area do
        = label_tag('Adminnote', 'Admin note:', for: 'adminnote')
        = text_area_tag(:adminnote, '', placeholder: 'Please explain the reason for the deletion...', class: 'form-control')

- content_for :ready_function do
  :plain
    initializeUserConfigurationDatatable();
    $('#delete-user-modal').on('show.bs.modal', function (event) {
      var link = $(event.relatedTarget);
      $(this).find('.user-login').text(link.data('user-login'));
      $(this).find('form').attr('action', link.data('action'));
    });

src/api/app/views/webui/users/new.html.haml
.card.mb-3
  .card-body
    .col-lg-6.ps-0
      - if can_register?
        %h3= @pagetitle.titleize
        = render 'webui/users/sign_up', submit_btn_text: 'Create'
      - else
        %p Sorry, sign up is disabled

src/api/app/views/webui/users/show.html.haml
:ruby
  @pagetitle = @is_displayed_user ? 'Your Profile' : "Profile of #{@displayed_user}"

  content_for(:meta_title, @pagetitle)
  content_for(:meta_image, gravatar_url(@displayed_user.email))

.row
  .col-12.col-md-4.col-xxl-3
    = render partial: 'webui/user/info', locals: { user: @displayed_user,
                                                   is_user: @is_displayed_user,
                                                   groups: @groups,
                                                   role_titles: @role_titles,
                                                   account_edit_link: @account_edit_link }
  .col-12.col-md-8.col-xxl-9.ps-md-0
    - locals = { involved_items_service: @involved_items_service,
                 comments: @comments,
                 displayed_user: @displayed_user }
    - locals.merge!({ activities_per_year: @activities_per_year,
                      first_day: @first_day,
                      last_day: @last_day,
                      date: @date,
                      activities_per_day: @activities_per_day }) if contribution_graph?
    = render partial: 'webui/user/involvement_and_activity', locals: locals
  - content_for :ready_function do
    :plain
        // Show biography characters counter
        $('body').on('focus keyup keydown', '#user_biography', function(e) {
          updateCharactersCount(e);
        });
        // Hide biography characters counter
        $('body').on('focusout', '#user_biography', function() {
          $('#bio-chars-counter').css("visibility", "hidden");
        });

- if @is_displayed_user
  = render partial: 'webui/user/password_dialog', locals: { user: @displayed_user }

src/api/app/views/webui/users/update.js.haml
resetFormValidation();
- if @displayed_user.errors.any?
  - @displayed_user.errors.messages.each do |field, messages|
    element = $("##{@displayed_user.class.name.underscore}_#{field}"); // Create strings like "user_email"
    setFormValidation(element, "#{messages.to_sentence}");
- else
  - locals = { user: @displayed_user, role_titles: @role_titles, account_edit_link: @account_edit_link, configuration: @configuration }
  :plain
    $('.in-place-editing').animate({
      opacity: 0.25
    }, 400, function() {
      scrollToInPlace();
      $('.in-place-editing').html(
        "#{escape_javascript(render(partial: 'webui/user/basic_info', locals: locals))}");
      setCollapsible();
      $('.in-place-editing').animate({ opacity: 1 }, 400, function() {
        $('#flash').html("#{escape_javascript(render(layout: false, partial: 'layouts/webui/flash', object: flash))}");
      });
    });